version: "3"

services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
  minio:
    image: minio/minio
    command: "server /data"
    ports:
      - "9000:9000"
    volumes:
      - data:/data
  web:
    build: .
    env_file: .env
    command: mix phx.server
    volumes:
      - .:/app
      - node_modules:/app/assets/node_modules
      - build:/app/_build
    ports:
      - "80:80"
    depends_on:
      - db

volumes:
  node_modules:
  build:
  data: